apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: personajes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3  # Ajusta según sea necesario
  selector:
    matchLabels:
      app: personajes
  template:
    metadata:
      labels:
        app: personajes
    spec:
      containers:
        - name: personajes-container
          image: personajes_rickymorty:latest  # Ajusta según sea necesario
          ports:
            - containerPort: 80
